#ifndef MS_LIB_GLOBAL_CONST_H
#define MS_LIB_GLOBAL_CONST_H

#define MS_CFG_GROUP_GLOBAL "Global"
#define UMM_LISTEN_PORT 7760
#define UMS_LISTEN_PORT 7770
#define MS_LISTEN_PORT 7780
#define MS_LUOXI_PORT 7790

#endif // MS_LIB_GLOBAL_CONST_H